jobs:
  deploy-staging:
    docker:
      - image: cimg/node:18.16
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - aws-eb/setup
      - run:
          name: Deploy to Staging
          command: |
            export AWS_DEFAULT_REGION=$AWS_REGION
            eb init ca-app -p node.js --region eu-north-1 || echo "Initialization already performed"
            eb deploy devops-ca-env

  deploy-production:
    docker:
      - image: cimg/node:18.16
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - aws-eb/setup
      - run:
          name: Deploy to Production
          command: |
            export AWS_DEFAULT_REGION=$AWS_REGION
            eb init ca-app -p node.js --region eu-north-1 || echo "Initialization already performed"
            eb deploy devops-ca-env

workflows:
  ci-cd-pipeline:
    jobs:
      - build-and-test
      - deploy-staging:
          requires:
            - build-and-test
          filters:
            branches:
              only: staging
      - deploy-production:
          requires:
            - deploy-staging
          filters:
            branches:
              only: main