version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Встановлення залежностей
          command: npm install
      - run:
          name: Запуск тестів
          command: npm test
      - run:
          name: Побудова додатку
          command: npm run build || echo "Немає кроку побудови"
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-staging:
    docker:
      - image: cimg/node:18.16
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - aws-eb/setup
      - run:
          name: Розгортання на Staging
          command: |
            eb init my-app-staging -p node.js --region us-east-1
            eb deploy my-app-staging-env

  deploy-production:
    docker:
      - image: cimg/node:18.16
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - aws-eb/setup
      - run:
          name: Розгортання на Production
          command: |
            eb init my-app-prod -p node.js --region us-east-1
            eb deploy my-app-prod-env

workflows:
  ci-cd-pipeline:
    jobs:
      - build-and-test
      - deploy-staging:
          requires:
            - build-and-test
          filters:
            branches:
              only: staging
      - deploy-production:
          requires:
            - deploy-staging
          filters:
            branches:
              only: main