version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - persist_to_workspace:
          root: . 
          paths:
            - .

  deploy-staging:
    docker:
      - image: cimg/node:18.16
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup
      - run:
          name: Install EB CLI
          command: |
            sudo apt-get update && sudo apt-get install -y python3-pip
            pip3 install awsebcli --upgrade --user
            export PATH=~/.local/bin:$PATH
      - run:
          name: Deploy to Staging
          command: |
            export AWS_DEFAULT_REGION=$AWS_REGION
            eb init ca-app -p node.js --region eu-north-1 || echo "Initialization already performed"
            eb deploy devops-ca-env

  deploy-production:
    docker:
      - image: cimg/node:18.16
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup
      - run:
          name: Install EB CLI
          command: |
            sudo apt-get update && sudo apt-get install -y python3-pip
            pip3 install awsebcli --upgrade --user
            export PATH=~/.local/bin:$PATH
      - run:
          name: Deploy to Production
          command: |
            export AWS_DEFAULT_REGION=$AWS_REGION
            eb init ca-app -p node.js --region eu-north-1 || echo "Initialization already performed"
            eb deploy devops-ca-env

workflows:
  ci-cd-pipeline:
    jobs:
      - build-and-test
      - deploy-staging:
          requires:
            - build-and-test
          filters:
            branches:
              only: staging
      - deploy-production:
          requires:
            - build-and-test
          filters:
            branches:
              only: main